#!/usr/bin/env bash

######################################
# REQUIRES AT LEAST swi-prolog 7.X.X #
######################################

basedir=$(pwd)

cd /tmp
mkdir srs
cd srs
# Can't use the latest version. See:
# http://www.postgresql.org/message-id/1420793104.20163.7.camel@uniklinik-freiburg.de
wget https://ftp.postgresql.org/pub/odbc/versions/src/psqlodbc-09.03.0300.tar.gz
tar xvf psqlod*
cd psql*
./configure
make
make install

echo "[nerdz]
Driver=PostgreSQL Unicode
Servername=localhost
Port=5432
Database=nerdz
Username=nerdz
Password=nerdz
Protocol=9.3.4
ReadOnly=yes
Debug=1

[srs]
Driver=PostgreSQL Unicode
Servername=localhost
Port=5432
Database=srs
Username=srs
Password=srs
Protocol=9.3.4
ReadOnly=no
Debug=1" >> /etc/odbc.ini

echo "[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=/usr/local/lib/psqlodbcw.so
Debug=0
CommLog=1
UsageCount=1" >> /etc/odbcinst.ini

cd ..
rm -rf psqlod*

createuser -U postgres -D -R -S srs
createdb -U postgres -O srs srs

cd $basedir

bash populate_db

cd cpp
mkdir -p ../bin
swipl-ld -o ../bin/srs *.cpp ../include/*.cpp ../../prolog/srs.pl -O -g -Wall -c++ clang++ -cc-options,-std=c++14 -ld-options=-lpthread

cp ../bin/srs /opt
cp ../../misc/systemd/srs.service /etc/systemd/system/

echo "[+] Setup completed"; echo
